(()=>{
  const defaults={
    objects:{category:'nitunxiang',subcategory:'',title:['HOW OBJECTS ENTER EVERYDAY LIFE','器物如何进入日常'],categoryLabel:['NITUNXIANG','泥吞象'],type:['ESSAY 001','文章 001'],date:'31.08.26',read:'6 MIN READ',images:['assets/published-data/65915db832b3622338fa61cc.webp','assets/published-data/ab5d4202803a92bde60065f2.webp','assets/published-data/143e5d75f414756e4762dce3.webp'],dek:['Beginning with material, touch and the traces left by use, we reconsider the relationship between an object and the body.','我们从材料、触感和使用留下的痕迹出发，重新理解一件物品与身体之间的关系。'],tags:[['Objects','器物'],['Culture','文化'],['Essay','文章']]},
    material:{category:'freedom',subcategory:'',title:['THE MEMORY OF MATERIAL','材料的记忆'],categoryLabel:['FREEDOM WITH WISDOM','自由明智'],type:['PROCESS 002','过程 002'],date:'18.08.26',read:'5 MIN READ',images:['assets/catalog/product-10.webp','assets/catalog/product-9.webp','assets/catalog/product-8.webp'],dek:['A study of how pressure, heat and time remain present in the finished form.','关于压力、温度与时间如何留存在最终形态之中的研究。'],tags:[['Material','材料'],['Process','过程']]},
    slowly:{category:'nomadic',subcategory:'spiritual',title:['WHY WE MAKE SLOWLY','缓慢制作的理由'],categoryLabel:['NOMADIC SERIES','游牧系列'],type:['STUDIO 003','工作室 003'],date:'02.07.26',read:'7 MIN READ',images:['assets/catalog/product-11.webp','assets/catalog/product-12.webp','assets/catalog/product-13.webp'],dek:['Each article can retain its own date, category and cover. Generous space and an editorial rhythm keep the page from feeling like a conventional blog list.','不同文章可以保留各自的发布日期、类别和封面。页面采用留白与大字号节奏，避免传统博客的资讯列表感。'],tags:[['Studio','工作室'],['Craft','手工艺']]}
  };
  const clone=(value)=>JSON.parse(JSON.stringify(value));
  let catalog=clone(defaults);
  try{catalog={...catalog,...JSON.parse(localStorage.getItem('ntx-article-catalog-v1')||'{}')}}catch(_){}
  const titleCase=(value)=>String(value||'').toLowerCase().replace(/\b[\p{L}\p{N}][\p{L}\p{N}'’-]*\b/gu,(word)=>word.charAt(0).toUpperCase()+word.slice(1));
  const normalizeTitles=()=>Object.values(catalog).forEach((article)=>{if(article?.title?.[0])article.title[0]=titleCase(article.title[0])});
  normalizeTitles();
  const renderList=()=>document.querySelectorAll('.article-row').forEach((row)=>{const key=row.querySelector('[data-list-gallery]')?.dataset.listGallery,data=catalog[key];if(!data)return;row.dataset.articleCategory=data.category||'nitunxiang';row.dataset.articleSubcategory=data.subcategory||'';const title=row.querySelector('.story-copy h2'),summary=row.querySelector('.story-copy>p'),type=row.querySelector('.story-meta span'),date=row.querySelector('.story-meta time'),tags=[...row.querySelectorAll('.article-tags span')];if(title){title.dataset.biEn=data.title?.[0]||'';title.dataset.biZh=data.title?.[1]||'';title.textContent=data.title?.[0]||''}if(summary){summary.dataset.biEn=data.dek?.[0]||'';summary.dataset.biZh=data.dek?.[1]||'';summary.textContent=data.dek?.[0]||''}if(type){type.dataset.biEn=data.type?.[0]||'';type.dataset.biZh=data.type?.[1]||'';type.textContent=data.type?.[0]||''}if(date)date.textContent=data.date||'';tags.forEach((tag,index)=>{const value=data.tags?.[index];tag.hidden=!value;if(value){tag.dataset.biEn=value[0];tag.dataset.biZh=value[1];tag.textContent=value[0]}})});
  const emit=()=>{renderList();document.dispatchEvent(new CustomEvent('ntx:articles-updated',{detail:{catalog}}))};
  const endpoint=()=>location.protocol==='file:'?'http://127.0.0.1:4173':new URL('.',location.href).href.replace(/\/$/,'');
  const load=async()=>{try{const localPreview=location.protocol==='file:'||['127.0.0.1','localhost'].includes(location.hostname);let response=await fetch(endpoint()+(localPreview?'/api/site-draft':'/api/site-state'),{cache:'no-store'});if(!response.ok&&localPreview)response=await fetch(endpoint()+'/api/site-state',{cache:'no-store'});if(response.ok){const state=await response.json();if(state.articleCatalog)catalog={...catalog,...state.articleCatalog};normalizeTitles();localStorage.setItem('ntx-article-catalog-v1',JSON.stringify(catalog));emit();}}catch(_){}return catalog};
  const save=async()=>{localStorage.setItem('ntx-article-catalog-v1',JSON.stringify(catalog));emit();for(const path of ['/api/site-draft','/api/site-state']){const current=await fetch(endpoint()+path,{cache:'no-store'});const state=current.ok?await current.json():{};const response=await fetch(endpoint()+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...state,articleCatalog:catalog})});if(!response.ok)throw new Error(`${response.status} ${response.statusText}`)}return catalog};
  let ready=Promise.resolve(catalog);
  const templateStyles=(editing)=>Object.fromEntries(Object.entries(editing||{}).map(([field,value])=>[field,{styles:clone(value?.styles||{})}]));
  const update=async(key,changes)=>{await ready;catalog[key]={...(catalog[key]||{}),...changes};normalizeTitles();if(key==='objects'&&changes.detailEditing){const template=templateStyles(changes.detailEditing);Object.keys(catalog).filter((articleKey)=>articleKey!=='objects').forEach((articleKey)=>{const current=catalog[articleKey]?.detailEditing||{};const merged=clone(current);Object.entries(template).forEach(([field,value])=>{merged[field]={...(merged[field]||{}),styles:{...(value.styles||{}),...(merged[field]?.styles||{})}}});catalog[articleKey]={...catalog[articleKey],detailEditing:merged}})}await save();return catalog[key]};
  window.NTX_ARTICLES={get:(key)=>catalog[key]||catalog.objects,all:()=>catalog,load,update,save,ready};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',renderList);else renderList();
  ready=load();window.NTX_ARTICLES.ready=ready;
  addEventListener('storage',(event)=>{if(event.key!=='ntx-article-catalog-v1'||!event.newValue)return;try{catalog={...catalog,...JSON.parse(event.newValue)};emit()}catch(_){}});
})();
