if(!document.querySelector('script[data-shared-language-notice]')){const sharedNoticeScript=document.createElement('script');sharedNoticeScript.src='language-notice.js?v=1';sharedNoticeScript.dataset.sharedLanguageNotice='';document.head.append(sharedNoticeScript);}
const grid=document.querySelector('[data-gene-gallery]');
const groupIndex=Number(document.body.dataset.geneGroup||0);
const galleryMenu=document.querySelector('[data-gallery-menu]'),galleryNav=document.querySelector('[data-gallery-nav]');galleryMenu?.addEventListener('click',()=>galleryNav?.classList.toggle('open'));galleryNav?.querySelectorAll('a').forEach((link)=>link.addEventListener('click',()=>galleryNav.classList.remove('open')));
const galleryHeader=document.querySelector('.gene-gallery-header');if(galleryHeader&&!galleryHeader.querySelector('.mobile-shop-link')){const shop=document.createElement('a');shop.className='mobile-shop-link';shop.href='catalog.html';shop.textContent='SHOP↗';shop.setAttribute('aria-label','进入商店');galleryHeader.append(shop);}
const activateMeta=(meta)=>{if(!meta)return;meta.classList.remove('is-active');requestAnimationFrame(()=>meta.classList.add('is-active'));clearTimeout(meta._activeTimer);meta._activeTimer=setTimeout(()=>meta.classList.remove('is-active'),320);};
document.querySelectorAll('[data-meta-en][data-meta-zh]').forEach((node)=>{const value=(language)=>language==='zh'?node.dataset.metaZh:(matchMedia('(max-width:760px)').matches&&node.dataset.metaMobileEn?node.dataset.metaMobileEn:node.dataset.metaEn);node.dataset.language='en';node.textContent=value('en');node.addEventListener('click',(event)=>{event.preventDefault();event.stopPropagation();activateMeta(node.closest('.gene-page-meta'));const language=node.dataset.language==='en'?'zh':'en';node.dataset.language=language;node.textContent=value(language);});});
document.querySelectorAll('.gene-page-meta .gene-page-arrow').forEach((arrow)=>arrow.addEventListener('click',(event)=>{if(event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;event.preventDefault();event.stopPropagation();const meta=arrow.closest('.gene-page-meta');activateMeta(meta);setTimeout(()=>{location.href=arrow.href;},220);}));
if(matchMedia('(max-width:760px)').matches){galleryHeader?.querySelectorAll('a').forEach((link)=>link.addEventListener('click',(event)=>{if(event.defaultPrevented||event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;const target=link.getAttribute('href');if(!target||target==='#')return;event.preventDefault();if(link.classList.contains('is-activating'))return;link.classList.add('is-activating');setTimeout(()=>{location.href=link.href;},230);}));}
const portable=(value)=>{if(typeof value!=='string')return value;const normalized=value.replace(/\\/g,'/'),marker='/assets/',index=normalized.toLowerCase().indexOf(marker);return index>=0?`assets/${normalized.slice(index+marker.length)}`:normalized;};
const localPreview=location.hostname==='127.0.0.1'||location.hostname==='localhost';let loadedState={};
async function loadImages(){try{const path=localPreview?'/api/site-draft':new URL('api/site-state',location.href).href;const response=await fetch(path,{cache:'no-store'});if(!response.ok)return;loadedState=await response.json();const values=loadedState.geneImageGroups?.[groupIndex]||(loadedState.geneImages?.length===24?loadedState.geneImages.slice(groupIndex*12,groupIndex*12+12):loadedState.geneImages?.slice(groupIndex*6,groupIndex*6+6));if(values)grid.querySelectorAll('img').forEach((image,index)=>{if(values[index])image.src=portable(values[index]);});}catch(_){}}
function reveal(){grid.querySelectorAll('figure').forEach((figure,index)=>setTimeout(()=>figure.classList.add('is-visible'),90*index));}
const title=document.querySelector('[data-gallery-title]'),editor=document.querySelector('[data-gallery-editor]'),status=document.querySelector('[data-title-status]');
const geneViewMode=matchMedia('(max-width:760px)').matches?'mobile':'desktop';
const legacyGeneCopyKey=`nitunxiang-gene-copy-v1:${groupIndex}`;
const geneCopyKey=`${legacyGeneCopyKey}:${geneViewMode}`;
if(geneViewMode==='mobile'&&!localStorage.getItem(geneCopyKey)&&localStorage.getItem(legacyGeneCopyKey))localStorage.setItem(geneCopyKey,localStorage.getItem(legacyGeneCopyKey));
const fontMap={sourcehan:'"NTX Source Han","Songti SC",serif',bigcaslon:'"NTX Big Caslon","Times New Roman",serif',sans:'Arial,"PingFang SC",sans-serif'};
const descriptionDefaults=groupIndex===0?{zh:'从中国文化与非物质文化遗产中寻找材料、技艺与精神结构，让传统在当代生活中继续生长。',en:'DRAWING MATERIALS, CRAFT AND SPIRITUAL STRUCTURES FROM CHINESE CULTURE AND INTANGIBLE HERITAGE, ALLOWING TRADITION TO GROW WITHIN CONTEMPORARY LIFE.'}:{zh:'以当代艺术与设计为方法，持续探索器物、身体、空间与日常生活之间的新关系。',en:'USING CONTEMPORARY ART AND DESIGN AS METHODS TO EXPLORE NEW RELATIONSHIPS BETWEEN OBJECTS, THE BODY, SPACE AND EVERYDAY LIFE.'};
const descriptionSection=document.createElement('section');descriptionSection.className='gene-gallery-description';descriptionSection.innerHTML='<p data-gallery-description></p>';title.closest('.gene-gallery-title').after(descriptionSection);const description=descriptionSection.querySelector('p');
const initialField=editor.querySelector('[data-title-initial]').closest('label');['en','zh'].forEach((language)=>{const label=document.createElement('label');label.textContent=language==='zh'?'中文介绍':'英文介绍';const textarea=document.createElement('textarea');textarea.dataset.descriptionInput=language;label.append(textarea);initialField.before(label);});
[{key:'title',label:'大标题字号',min:24,max:160,value:96},{key:'description',label:'介绍字号',min:8,max:36,value:12}].forEach((item)=>{const label=document.createElement('label');label.textContent=item.label;const input=document.createElement('input');input.type='number';input.min=item.min;input.max=item.max;input.step='1';input.value=item.value;input.dataset.gallerySize=item.key;label.append(input);initialField.before(label);});
const descriptionLineHeightLabel=document.createElement('label');descriptionLineHeightLabel.textContent='引言行间距';const descriptionLineHeightInput=document.createElement('input');descriptionLineHeightInput.type='number';descriptionLineHeightInput.min='1';descriptionLineHeightInput.max='3';descriptionLineHeightInput.step='.05';descriptionLineHeightInput.value='1.75';descriptionLineHeightInput.dataset.galleryLineHeight='description';descriptionLineHeightLabel.append(descriptionLineHeightInput);initialField.before(descriptionLineHeightLabel);
[{key:'title',label:'大标题字重'},{key:'description',label:'介绍字重'}].forEach((item)=>{const label=document.createElement('label');label.textContent=item.label;const select=document.createElement('select');select.dataset.galleryWeight=item.key;[200,300,400,500,600,700,800,900].forEach((weight)=>{const option=document.createElement('option');option.value=weight;option.textContent=weight;select.append(option);});label.append(select);initialField.before(label);});
const alignmentControl=document.createElement('div');alignmentControl.className='gallery-alignment-control';alignmentControl.innerHTML='<strong>文字对齐</strong><div class="gallery-align-row"><span>大标题</span><div><button type="button" data-gallery-align="title:left">居左</button><button type="button" data-gallery-align="title:center">居中</button><button type="button" data-gallery-align="title:right">居右</button></div></div><div class="gallery-align-row"><span>引言</span><div><button type="button" data-gallery-align="description:left">居左</button><button type="button" data-gallery-align="description:center">居中</button><button type="button" data-gallery-align="description:right">居右</button></div></div>';initialField.before(alignmentControl);
const positionControl=document.createElement('div');positionControl.className='gallery-position-control';positionControl.innerHTML='<strong>大标题位置微调</strong><label>左右位置 <output data-position-value="x">0 px</output><input type="range" min="-200" max="200" step="1" value="0" data-title-position="x"></label><label>上下位置 <output data-position-value="y">0 px</output><input type="range" min="-120" max="120" step="1" value="0" data-title-position="y"></label><button type="button" data-title-center>恢复居中</button>';initialField.before(positionControl);
const geneMetaNodes=[...document.querySelectorAll('[data-meta-en][data-meta-zh]')];
const defaultMetaTexts=geneMetaNodes.map((node)=>({en:node.dataset.metaEn,zh:node.dataset.metaZh,mobileEn:node.dataset.metaMobileEn||''}));
let titleData={zh:title.dataset.titleZh.replace(/\\n/g,'\n'),en:title.dataset.titleEn.replace(/\\n/g,'\n'),description:{...descriptionDefaults},metaTexts:defaultMetaTexts,initial:'en',fonts:{zh:'sourcehan',en:'bigcaslon'},descriptionFonts:{zh:'sourcehan',en:'sans'},sizes:{title:{zh:96,en:64},description:{zh:12,en:12}},weights:{title:{zh:400,en:400},description:{zh:400,en:400}},lineHeights:{description:{zh:1.75,en:1.75}},alignments:{title:{zh:'center',en:'center'},description:{zh:'center',en:'center'}},positions:{zh:{x:0,y:0},en:{x:0,y:0}}},titleLanguage='en';
function applyMetaTexts(){geneMetaNodes.forEach((node,index)=>{const values=titleData.metaTexts?.[index]||defaultMetaTexts[index];node.dataset.metaEn=values.en;node.dataset.metaZh=values.zh;if(values.mobileEn)node.dataset.metaMobileEn=values.mobileEn;const language=node.dataset.language||'en';node.textContent=language==='zh'?values.zh:(matchMedia('(max-width:760px)').matches&&values.mobileEn?values.mobileEn:values.en);});}
document.addEventListener('ntx-gene-meta-edit',(event)=>{const node=event.detail?.node,index=geneMetaNodes.indexOf(node),language=event.detail?.language;if(index<0||!['en','zh'].includes(language))return;titleData.metaTexts=titleData.metaTexts||defaultMetaTexts.map((value)=>({...value}));titleData.metaTexts[index]={...defaultMetaTexts[index],...titleData.metaTexts[index],[language]:event.detail.value};applyMetaTexts();});
const renderTitle=(language)=>{titleLanguage=language;title.innerHTML=titleData[language].split('\n').map((line)=>line.replace(/&/g,'&amp;').replace(/</g,'&lt;')).join('<br>');title.style.fontFamily=fontMap[titleData.fonts[language]];title.style.fontWeight=titleData.weights.title[language];title.style.setProperty('--gallery-title-size',`${titleData.sizes.title[language]}px`);title.style.setProperty('--gallery-title-x',`${titleData.positions[language].x}px`);title.style.setProperty('--gallery-title-y',`${titleData.positions[language].y}px`);title.style.textAlign=titleData.alignments.title[language];title.dataset.language=language;description.textContent=titleData.description[language];description.style.fontFamily=fontMap[language==='zh'?'sourcehan':'bigcaslon'];description.style.fontSize=`${titleData.sizes.description[language]}px`;description.style.fontWeight=titleData.weights.description[language];description.style.lineHeight=titleData.lineHeights.description[language];description.style.textAlign='center';description.dataset.language=language;document.querySelector('[data-gallery-size="title"]').value=titleData.sizes.title[language];document.querySelector('[data-gallery-size="description"]').value=titleData.sizes.description[language];document.querySelector('[data-gallery-weight="title"]').value=titleData.weights.title[language];document.querySelector('[data-gallery-weight="description"]').value=titleData.weights.description[language];descriptionLineHeightInput.value=titleData.lineHeights.description[language];document.querySelectorAll('[data-gallery-align]').forEach((button)=>{const [target,alignment]=button.dataset.galleryAlign.split(':');button.classList.toggle('is-active',target==='description'?alignment==='center':titleData.alignments[target][language]===alignment);});['x','y'].forEach((axis)=>{document.querySelector(`[data-title-position="${axis}"]`).value=titleData.positions[language][axis];document.querySelector(`[data-position-value="${axis}"]`).textContent=`${titleData.positions[language][axis]} px`;});};
function loadTitle(){const stored=loadedState.geneGalleryTitles?.[groupIndex],saved=stored?.views?.[geneViewMode]||stored;if(saved)titleData={...titleData,...saved,description:{...titleData.description,...saved.description},fonts:{...titleData.fonts,...saved.fonts},sizes:{title:{...titleData.sizes.title,...saved.sizes?.title},description:{...titleData.sizes.description,...saved.sizes?.description}},weights:{title:{...titleData.weights.title,...saved.weights?.title},description:{...titleData.weights.description,...saved.weights?.description}},lineHeights:{description:{...titleData.lineHeights.description,...saved.lineHeights?.description}},alignments:{title:{...titleData.alignments.title,...saved.alignments?.title},description:{...titleData.alignments.description,...saved.alignments?.description}},positions:{zh:{...titleData.positions.zh,...saved.positions?.zh},en:{...titleData.positions.en,...saved.positions?.en}}};document.querySelector('[data-title-input="zh"]').value=titleData.zh;document.querySelector('[data-title-input="en"]').value=titleData.en;document.querySelector('[data-description-input="zh"]').value=titleData.description.zh;document.querySelector('[data-description-input="en"]').value=titleData.description.en;document.querySelector('[data-title-initial]').value=titleData.initial;document.querySelector('[data-title-font="zh"]').value=titleData.fonts.zh;document.querySelector('[data-title-font="en"]').value=titleData.fonts.en;renderTitle(titleData.initial);}
title.addEventListener('click',()=>renderTitle(titleLanguage==='zh'?'en':'zh'));
description.addEventListener('click',()=>renderTitle(titleLanguage==='zh'?'en':'zh'));
document.querySelector('[data-gallery-editor-launch]')?.addEventListener('click',()=>editor.classList.add('is-open'));document.querySelector('[data-gallery-editor-close]')?.addEventListener('click',()=>editor.classList.remove('is-open'));
document.querySelectorAll('[data-title-input]').forEach((input)=>input.addEventListener('input',()=>{titleData[input.dataset.titleInput]=input.value;renderTitle(titleLanguage);}));document.querySelector('[data-title-initial]')?.addEventListener('change',(event)=>{titleData.initial=event.target.value;renderTitle(titleData.initial);});document.querySelectorAll('[data-title-font]').forEach((select)=>select.addEventListener('change',()=>{titleData.fonts[select.dataset.titleFont]=select.value;renderTitle(titleLanguage);}));
document.querySelectorAll('[data-description-input]').forEach((input)=>input.addEventListener('input',()=>{titleData.description[input.dataset.descriptionInput]=input.value;renderTitle(titleLanguage);}));
document.querySelectorAll('[data-gallery-size]').forEach((input)=>input.addEventListener('input',()=>{const value=Math.max(Number(input.min),Math.min(Number(input.max),Number(input.value)||Number(input.min)));titleData.sizes[input.dataset.gallerySize][titleLanguage]=value;renderTitle(titleLanguage);}));
document.querySelectorAll('[data-gallery-weight]').forEach((select)=>select.addEventListener('change',()=>{titleData.weights[select.dataset.galleryWeight][titleLanguage]=Number(select.value);renderTitle(titleLanguage);}));
descriptionLineHeightInput.addEventListener('input',()=>{titleData.lineHeights.description[titleLanguage]=Math.max(1,Math.min(3,Number(descriptionLineHeightInput.value)||1.75));renderTitle(titleLanguage);status.textContent=`${titleLanguage==='zh'?'中文':'英文'}引言行间距已调整，请保存`;});
document.querySelectorAll('[data-gallery-align]').forEach((button)=>button.addEventListener('click',()=>{const [target,alignment]=button.dataset.galleryAlign.split(':');titleData.alignments[target][titleLanguage]=alignment;renderTitle(titleLanguage);status.textContent=`${target==='title'?'大标题':'引言'}已设为${alignment==='left'?'居左':alignment==='right'?'居右':'居中'}，请保存`; }));
document.querySelectorAll('[data-title-position]').forEach((input)=>input.addEventListener('input',()=>{titleData.positions[titleLanguage][input.dataset.titlePosition]=Number(input.value);renderTitle(titleLanguage);status.textContent='标题位置已微调，保存后生效';}));document.querySelector('[data-title-center]')?.addEventListener('click',()=>{titleData.positions[titleLanguage]={x:0,y:0};renderTitle(titleLanguage);status.textContent='标题已恢复居中';});
async function saveTitle(publish=false){saveLocalGeneCopy();loadedState.geneGalleryTitles=loadedState.geneGalleryTitles||[];const existing=loadedState.geneGalleryTitles[groupIndex]||{};loadedState.geneGalleryTitles[groupIndex]={...existing,views:{...(existing.views||{}),[geneViewMode]:JSON.parse(JSON.stringify(titleData))}};const post=async(path)=>{const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(loadedState)});if(!response.ok)throw new Error(response.statusText);};try{await post('/api/site-draft');if(publish)await post('/api/site-state');status.textContent=`✓ ${geneViewMode==='mobile'?'手机端':'网页端'}${publish?'已发布':'已保存'}`;return true;}catch(error){status.textContent=`保存失败：${error.message}`;return false;}}
function saveLocalGeneCopy(){try{localStorage.setItem(geneCopyKey,JSON.stringify(titleData));}catch(_){}}
function loadLocalGeneCopy(){try{const local=JSON.parse(localStorage.getItem(geneCopyKey)||'null');if(!local)return;titleData={...titleData,...local,description:{...titleData.description,...local.description},fonts:{...titleData.fonts,...local.fonts},descriptionFonts:{...titleData.descriptionFonts,...local.descriptionFonts},sizes:{title:{...titleData.sizes.title,...local.sizes?.title},description:{...titleData.sizes.description,...local.sizes?.description}},weights:{title:{...titleData.weights.title,...local.weights?.title},description:{...titleData.weights.description,...local.weights?.description}},lineHeights:{description:{...titleData.lineHeights.description,...local.lineHeights?.description}},alignments:{title:{...titleData.alignments.title,...local.alignments?.title},description:{...titleData.alignments.description,...local.alignments?.description}},positions:{zh:{...titleData.positions.zh,...local.positions?.zh},en:{...titleData.positions.en,...local.positions?.en}}};document.querySelector('[data-title-input="zh"]').value=titleData.zh;document.querySelector('[data-title-input="en"]').value=titleData.en;document.querySelector('[data-description-input="zh"]').value=titleData.description.zh;document.querySelector('[data-description-input="en"]').value=titleData.description.en;renderTitle(titleData.initial);}catch(_){}}
document.querySelector('[data-title-save]')?.addEventListener('click',()=>saveTitle(false));document.querySelector('[data-title-publish]')?.addEventListener('click',()=>saveTitle(true));
loadImages().then(()=>{loadTitle();loadLocalGeneCopy();applyMetaTexts();}).finally(reveal);
