(()=>{
  if(document.body.classList.contains('home-page'))return;
  if(!document.querySelector('link[data-ntx-global-footer]')){const link=document.createElement('link');link.rel='stylesheet';link.href='global-footer.css?v=1';link.dataset.ntxGlobalFooter='';document.head.append(link)}
  const footer=document.querySelector('footer');if(!footer)return;
  footer.className='ntx-global-footer';footer.id=footer.id||'contact';
  footer.innerHTML='<div class="ntx-footer-bar"><span data-footer-bi data-bi-en="© NITUNXIANG" data-bi-zh="© 泥吞象">© NITUNXIANG</span><i aria-hidden="true">|</i><a href="#" data-footer-xiaohongshu data-footer-bi data-bi-en="Xiaohongshu" data-bi-zh="小红书">Xiaohongshu</a><i aria-hidden="true">|</i><a href="#" data-footer-weixin data-footer-bi data-bi-en="Weixin" data-bi-zh="微信">Weixin</a><i aria-hidden="true">|</i><a href="mailto:studio@example.com" data-footer-email>studio@example.com</a><i aria-hidden="true">|</i><span data-footer-bi data-bi-en="ALL RIGHTS RESERVED" data-bi-zh="版权所有">ALL RIGHTS RESERVED</span></div>';
  const renderLanguage=(language)=>footer.querySelectorAll('[data-footer-bi]').forEach((node)=>{node.textContent=node.dataset[language==='zh'?'biZh':'biEn'];node.lang=language==='zh'?'zh-CN':'en'});let language='en';renderLanguage(language);
  document.addEventListener('click',(event)=>{if(!event.target.closest('[data-language-switch]'))return;setTimeout(()=>{const pageLanguage=document.querySelector('[data-bi-language]')?.dataset.biLanguage;language=pageLanguage==='zh'||pageLanguage==='en'?pageLanguage:(language==='en'?'zh':'en');renderLanguage(language)},0)});
  const local=location.protocol==='file:'||location.hostname==='127.0.0.1'||location.hostname==='localhost',endpoint=local?(location.protocol==='file:'?'http://127.0.0.1:4173/api/site-draft':'/api/site-draft'):new URL('api/site-state',location.href).href;
  fetch(endpoint,{cache:'no-store'}).then((response)=>response.ok?response.json():null).then((state)=>{const contact=state?.footerContact||{},xiaohongshu=footer.querySelector('[data-footer-xiaohongshu]'),weixin=footer.querySelector('[data-footer-weixin]'),email=footer.querySelector('[data-footer-email]');if(contact.xiaohongshu&&xiaohongshu)xiaohongshu.href=contact.xiaohongshu;if(contact.weixin&&weixin)weixin.href=contact.weixin;if(contact.email&&email){email.textContent=contact.email;email.href='mailto:'+contact.email}}).catch(()=>{});
})();
