const imageDb=()=>new Promise((resolve,reject)=>{const request=indexedDB.open('nitunxiang-media-v1',1);request.onupgradeneeded=()=>request.result.createObjectStore('images');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
async function putImage(key,value){const db=await imageDb();return new Promise((resolve,reject)=>{const tx=db.transaction('images','readwrite');tx.objectStore('images').put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
async function getImage(key){const db=await imageDb();return new Promise((resolve,reject)=>{const request=db.transaction('images').objectStore('images').get(key);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
const params=new URLSearchParams(location.search);const productId=params.get('id');
let mother;try{mother=JSON.parse(sessionStorage.getItem('nitunxiang-active-product'));}catch(_){}
if(!mother||mother.id!==productId){mother={id:productId||'demo',name:'商品页面',price:0,spec:'请从 Catalog 点击商品进入此页面',image:'assets/products/sku-01.webp',series:'泥吞象',seriesEn:'NITUNXIANG',subseries:'Product'};}
document.title=`${mother.name} — 泥吞象 NITUNXIANG`;document.querySelector('[data-page-number]').textContent=`N° ${String(mother.position||1).padStart(2,'0')}`;
let store={};try{store=JSON.parse(localStorage.getItem('nitunxiang-child-skus-v1'))||{};}catch(_){}
let variants=store[mother.id]||[{id:`${mother.id}-base`,name:mother.name,price:mother.price,spec:mother.spec,image:mother.image}];let activeId=variants[0]?.id;let pendingImage='';let editingId=null;let quantity=1;let bagCount=Number(localStorage.getItem('nitunxiang-bag-count')||0);
const q=(s)=>document.querySelector(s);const money=(n)=>`¥ ${Number(n||0).toLocaleString('zh-CN')}`;
async function save(){q('[data-variant-status]').textContent='正在保存子 SKU 与图片…';try{await Promise.all(variants.filter(v=>v.image?.startsWith('data:')).map(v=>putImage(`child:${v.id}`,v.image)));const compact={...store};compact[mother.id]=variants.map(v=>({...v,image:v.image?.startsWith('data:')?(mother.image?.startsWith('data:')?'':mother.image):v.image}));store=compact;localStorage.setItem('nitunxiang-child-skus-v1',JSON.stringify(store));q('[data-variant-status]').textContent='✓ 子 SKU 与高清图片均已保存';}catch(_){q('[data-variant-status]').textContent='保存失败，请确认浏览器允许本地数据存储';}}
function active(){return variants.find(v=>v.id===activeId)||variants[0];}
function render(){const item=active();if(!item)return;const index=variants.findIndex(v=>v.id===item.id);q('[data-main-image]').src=item.image||mother.image;q('[data-main-image]').alt=item.name;q('[data-series]').textContent=`${mother.subseries} · ${mother.series} / ${mother.seriesEn}`;q('[data-product-name]').textContent=item.name;q('[data-product-price]').textContent=money(item.price);q('[data-product-spec]').textContent=item.spec;q('[data-variant-count]').textContent=`${String(variants.length).padStart(2,'0')} SKU`;q('[data-image-index]').textContent=`${String(index+1).padStart(2,'0')} / ${String(variants.length).padStart(2,'0')}`;q('[data-variant-list]').innerHTML=variants.map(v=>`<button class="variant-chip${v.id===item.id?' active':''}" data-variant-id="${v.id}">${v.name}</button>`).join('');q('[data-thumbnail-list]').innerHTML=variants.map(v=>`<button class="thumb-button${v.id===item.id?' active':''}" data-variant-id="${v.id}" aria-label="查看 ${v.name}"><img src="${v.image||mother.image}" alt=""></button>`).join('');q('[data-quantity]').textContent=quantity;q('[data-add-total]').textContent=money(Number(item.price||0)*quantity);q('[data-bag-count]').textContent=bagCount;q('[data-child-manage-list]').innerHTML=variants.map((v,i)=>`<div class="child-manage-item"><strong>${v.name}</strong>${i?`<div class="child-actions"><button data-edit-child="${v.id}">编辑</button><button data-delete-child="${v.id}">删除</button></div>`:'<span></span>'}<small>${money(v.price)} · ${v.spec}</small></div>`).join('');}
q('[data-variant-list]').addEventListener('click',e=>{const button=e.target.closest('[data-variant-id]');if(button){activeId=button.dataset.variantId;render();}});
q('[data-thumbnail-list]').addEventListener('click',e=>{const button=e.target.closest('[data-variant-id]');if(button){activeId=button.dataset.variantId;render();}});
q('[data-qty-minus]').addEventListener('click',()=>{quantity=Math.max(1,quantity-1);render();});q('[data-qty-plus]').addEventListener('click',()=>{quantity=Math.min(99,quantity+1);render();});
q('[data-add-bag]').addEventListener('click',()=>{bagCount+=quantity;localStorage.setItem('nitunxiang-bag-count',String(bagCount));q('[data-purchase-status]').textContent=`✓ 已加入购物袋：${active().name} × ${quantity}`;q('[data-add-bag]').classList.add('added');setTimeout(()=>q('[data-add-bag]').classList.remove('added'),1200);render();});
q('[data-variant-editor-launch]').addEventListener('click',()=>{q('[data-variant-editor]').classList.add('open');q('[data-variant-editor]').setAttribute('aria-hidden','false');});q('[data-variant-close]').addEventListener('click',()=>{q('[data-variant-editor]').classList.remove('open');q('[data-variant-editor]').setAttribute('aria-hidden','true');});
q('[data-child-image]').addEventListener('click',()=>q('[data-child-image-input]').click());q('[data-child-image-input]').addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{pendingImage=reader.result;q('[data-variant-status]').textContent='图片已选择';};reader.readAsDataURL(file);});
function resetChildForm(){editingId=null;pendingImage='';q('[data-child-name]').value='';q('[data-child-price]').value='';q('[data-child-spec]').value='';q('[data-child-image-input]').value='';q('[data-child-add]').textContent='添加到当前商品页面';q('[data-child-cancel]').hidden=true;}
q('[data-child-cancel]').addEventListener('click',()=>{resetChildForm();q('[data-variant-status]').textContent='已取消编辑';});
q('[data-child-add]').addEventListener('click',async()=>{const name=q('[data-child-name]').value.trim();if(!name){q('[data-variant-status]').textContent='请填写子 SKU 名称';return;}const price=Math.max(0,Number(q('[data-child-price]').value)||0);const spec=q('[data-child-spec]').value.trim();if(editingId){const index=variants.findIndex(v=>v.id===editingId);if(index>-1){variants[index]={...variants[index],name,price,spec,image:pendingImage||variants[index].image||mother.image};activeId=editingId;}}else{const child={id:`${mother.id}-${Date.now()}`,name,price,spec,image:pendingImage||mother.image};variants.push(child);activeId=child.id;}const wasEditing=Boolean(editingId);resetChildForm();render();await save();q('[data-variant-status]').textContent=wasEditing?'✓ 子 SKU 修改已保存':'✓ 子 SKU 已添加';});
q('[data-child-manage-list]').addEventListener('click',async e=>{const editButton=e.target.closest('[data-edit-child]');if(editButton){const item=variants.find(v=>v.id===editButton.dataset.editChild);if(!item)return;editingId=item.id;pendingImage='';q('[data-child-name]').value=item.name;q('[data-child-price]').value=item.price;q('[data-child-spec]').value=item.spec||'';q('[data-child-add]').textContent='保存子 SKU 修改';q('[data-child-cancel]').hidden=false;q('[data-variant-status]').textContent='正在编辑；不重新选图会保留原图片';return;}const deleteButton=e.target.closest('[data-delete-child]');if(!deleteButton)return;if(editingId===deleteButton.dataset.deleteChild)resetChildForm();variants=variants.filter(v=>v.id!==deleteButton.dataset.deleteChild);activeId=variants[0]?.id;render();await save();});render();
Promise.all([getImage(`catalog:${mother.id}`).then(image=>{if(image){mother.image=image;const base=variants.find(v=>v.id===`${mother.id}-base`);if(base)base.image=image;}}).catch(()=>{}),...variants.map(async v=>{try{const image=await getImage(`child:${v.id}`);if(image)v.image=image;}catch(_){}})]).then(render);
if(matchMedia('(max-width:760px)').matches){document.querySelectorAll('.product-header a').forEach((link)=>link.addEventListener('click',(event)=>{if(event.defaultPrevented||event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;const target=link.getAttribute('href');if(!target||target==='#')return;event.preventDefault();if(link.classList.contains('is-nav-activating'))return;link.classList.add('is-nav-activating');setTimeout(()=>{location.href=link.href;},230);}));}
